name: Deployment

on:
  push:
    branches:
      - main

jobs:
  publish-and-deploy:
    name: Build and Push Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker Hub
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: "${{ secrets.DOCKER_USERNAME }}/cei-front"

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/cei-front:latest"
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy docker image to server
    runs-on: ubuntu-latest
    steps:

      - name: Debug secrets
        run: |
          echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "SERVICE_SSH_KEY is set: ${{ secrets.SERVICE_SSH_KEY != '' }}"
          echo "SERVER_USERNAME is set: ${{ secrets.SERVER_USERNAME != '' }}"
          echo "SERVER_HOST is set: ${{ secrets.SERVER_HOST != '' }}"

      - name: Pull and start image
        uses: appleboy/ssh-action@master
        env:
          DCKR_USRNM: ${{ secrets.DOCKER_USERNAME }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVICE_SSH_KEY }}
          envs: DCKR_USRNM
          script: |
            docker pull "$DCKR_USRNM/cei-front:latest"
            docker stop cei-app
            docker rm cei-app
            docker run -d -p 9000:80 --name cei-app "$DCKR_USRNM/cei-front:latest"
